/*
* This file was generated by the CommonAPI Generators. 
* Used org.genivi.commonapi.core 2.1.4.
* Used org.franca.core 0.8.9.
*
* 
*/
#include "Browser.h"

namespace org {
namespace genivi {
namespace MediaManager {

Browser::SortKey::SortKey(const SortOrder& orderValue, const std::string& keyNameValue):
        order(orderValue),
        keyName(keyNameValue)
{
}


bool operator==(const Browser::SortKey& lhs, const Browser::SortKey& rhs) {
    if (&lhs == &rhs)
        return true;

    return
        lhs.order == rhs.order &&
        lhs.keyName == rhs.keyName
    ;
}

void Browser::SortKey::readFromInputStream(CommonAPI::InputStream& inputStream) {
    inputStream >> order;
    inputStream >> keyName;
}

void Browser::SortKey::writeToOutputStream(CommonAPI::OutputStream& outputStream) const {
    outputStream << order;
    outputStream << keyName;
}

} // namespace MediaManager
} // namespace genivi
} // namespace org
