/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core Unknown.
* Used org.franca.core Unknown.
*
* 
*/
#ifndef ORG_GENIVI_MEDIAMANAGER_Browser_Types_H_
#define ORG_GENIVI_MEDIAMANAGER_Browser_Types_H_



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/InputStream.h>
#include <CommonAPI/OutputStream.h>
#include <CommonAPI/SerializableStruct.h>
#include <CommonAPI/types.h>
#include <cstdint>
#include <string>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace org {
namespace genivi {
namespace mediamanager {

namespace BrowserTypes {
    enum class SortOrder: int32_t {
        ASCENDING,
        DESCENDING
    };
    
    // Definition of a comparator still is necessary for GCC 4.4.1, topic is fixed since 4.5.1
    struct SortOrderComparator;
    struct SortKey: CommonAPI::SerializableStruct {
         SortOrder order;
         std::string keyName;
    
        SortKey() = default;
        SortKey(const SortOrder& order, const std::string& keyName);
    
    
        virtual void readFromInputStream(CommonAPI::InputStream& inputStream);
        virtual void writeToOutputStream(CommonAPI::OutputStream& outputStream) const;
    
        static inline void writeToTypeOutputStream(CommonAPI::TypeOutputStream& typeOutputStream) {
            typeOutputStream.writeInt32Type();
            typeOutputStream.writeStringType();
        }
    };
    enum class BrowserError: int32_t {
        NO_ERROR,
        NO_CONNECTION,
        BAD_PATH
    };
    
    // Definition of a comparator still is necessary for GCC 4.4.1, topic is fixed since 4.5.1
    struct BrowserErrorComparator;

bool operator==(const SortKey& lhs, const SortKey& rhs);
inline bool operator!=(const SortKey& lhs, const SortKey& rhs) {
    return !(lhs == rhs);
}
inline CommonAPI::InputStream& operator>>(CommonAPI::InputStream& inputStream, SortOrder& enumValue) {
    return inputStream.readEnumValue<int32_t>(enumValue);
}

inline CommonAPI::OutputStream& operator<<(CommonAPI::OutputStream& outputStream, const SortOrder& enumValue) {
    return outputStream.writeEnumValue(static_cast<int32_t>(enumValue));
}

struct SortOrderComparator {
    inline bool operator()(const SortOrder& lhs, const SortOrder& rhs) const {
        return static_cast<int32_t>(lhs) < static_cast<int32_t>(rhs);
    }
};

inline CommonAPI::InputStream& operator>>(CommonAPI::InputStream& inputStream, BrowserError& enumValue) {
    return inputStream.readEnumValue<int32_t>(enumValue);
}

inline CommonAPI::OutputStream& operator<<(CommonAPI::OutputStream& outputStream, const BrowserError& enumValue) {
    return outputStream.writeEnumValue(static_cast<int32_t>(enumValue));
}

struct BrowserErrorComparator {
    inline bool operator()(const BrowserError& lhs, const BrowserError& rhs) const {
        return static_cast<int32_t>(lhs) < static_cast<int32_t>(rhs);
    }
};



static inline const char* getTypeCollectionName() {
    static const char* typeCollectionName = "org.genivi.mediamanager.BrowserTypes";
    return typeCollectionName;
}

inline CommonAPI::Version getTypeCollectionVersion() {
    return CommonAPI::Version(1, 0);
}

} // namespace BrowserTypes

} // namespace mediamanager
} // namespace genivi
} // namespace org

namespace CommonAPI {

    template<>
    struct BasicTypeWriter<org::genivi::mediamanager::BrowserTypes::SortOrder> {
        inline static void writeType (CommonAPI::TypeOutputStream& typeStream) {
            typeStream.writeInt32EnumType();
        }
    };
    
    template<>
    struct InputStreamVectorHelper<org::genivi::mediamanager::BrowserTypes::SortOrder> {
        static void beginReadVector(InputStream& inputStream, const std::vector<org::genivi::mediamanager::BrowserTypes::SortOrder>& vectorValue) {
            inputStream.beginReadInt32EnumVector();
        }
    };
    
    template <>
    struct OutputStreamVectorHelper<org::genivi::mediamanager::BrowserTypes::SortOrder> {
        static void beginWriteVector(OutputStream& outputStream, const std::vector<org::genivi::mediamanager::BrowserTypes::SortOrder>& vectorValue) {
            outputStream.beginWriteInt32EnumVector(vectorValue.size());
        }
    };
    template<>
    struct BasicTypeWriter<org::genivi::mediamanager::BrowserTypes::BrowserError> {
        inline static void writeType (CommonAPI::TypeOutputStream& typeStream) {
            typeStream.writeInt32EnumType();
        }
    };
    
    template<>
    struct InputStreamVectorHelper<org::genivi::mediamanager::BrowserTypes::BrowserError> {
        static void beginReadVector(InputStream& inputStream, const std::vector<org::genivi::mediamanager::BrowserTypes::BrowserError>& vectorValue) {
            inputStream.beginReadInt32EnumVector();
        }
    };
    
    template <>
    struct OutputStreamVectorHelper<org::genivi::mediamanager::BrowserTypes::BrowserError> {
        static void beginWriteVector(OutputStream& outputStream, const std::vector<org::genivi::mediamanager::BrowserTypes::BrowserError>& vectorValue) {
            outputStream.beginWriteInt32EnumVector(vectorValue.size());
        }
    };

}


namespace std {
    //Hash for SortOrder
    template<>
    struct hash<org::genivi::mediamanager::BrowserTypes::SortOrder> {
        inline size_t operator()(const org::genivi::mediamanager::BrowserTypes::SortOrder& sortOrder) const {
            return static_cast<int32_t>(sortOrder);
        }
    };
    //Hash for BrowserError
    template<>
    struct hash<org::genivi::mediamanager::BrowserTypes::BrowserError> {
        inline size_t operator()(const org::genivi::mediamanager::BrowserTypes::BrowserError& browserError) const {
            return static_cast<int32_t>(browserError);
        }
    };
}

#endif // ORG_GENIVI_MEDIAMANAGER_Browser_Types_H_
