/*
* This file was generated by the CommonAPI Generators. 
* Used org.genivi.commonapi.core 2.1.4.
* Used org.franca.core 0.8.9.
*
* 
*/
#include "BrowserTypes.h"


namespace org {
namespace genivi {
namespace mediamanager {
namespace BrowserTypes {


SortKey::SortKey(const SortOrder& orderValue, const std::string& keyNameValue):
        order(orderValue),
        keyName(keyNameValue)
{
}


bool operator==(const SortKey& lhs, const SortKey& rhs) {
    if (&lhs == &rhs)
        return true;

    return
        lhs.order == rhs.order &&
        lhs.keyName == rhs.keyName
    ;
}

void SortKey::readFromInputStream(CommonAPI::InputStream& inputStream) {
    inputStream >> order;
    inputStream >> keyName;
}

void SortKey::writeToOutputStream(CommonAPI::OutputStream& outputStream) const {
    outputStream << order;
    outputStream << keyName;
}



} // namespace BrowserTypes
} // namespace mediamanager
} // namespace genivi
} // namespace org
