/*
* This file was generated by the CommonAPI Generators. 
* Used org.genivi.commonapi.core 2.1.4.
* Used org.franca.core 0.8.9.
*
* 
*/
/**
 * Indexer control interface. Allows administerial tasks for
                  the
 *  indexer backend, such as starting, stopping and requesting
                 
 *  status of the indexer.
                  For querying the database, please
 *  see
                  org.genivi.mediamanager.Browser
 */
#include "Indexer.h"

namespace org {
namespace genivi {
namespace mediamanager {

/**
 * RUNNING: The indexer is currently traversing files and/or
                     
 *           extracting metadata
                      STOPPED: The indexer has
 *  been stopped and will not start
                                 indexing by
 *  itself
                      IDLE:    The indexer has finished, and is waiting
 *  for new
                                 files to index
 */

} // namespace mediamanager
} // namespace genivi
} // namespace org
