/*
* This file was generated by the CommonAPI Generators. 
* Used org.genivi.commonapi.core 2.1.4.
* Used org.franca.core 0.8.9.
*
* 
*/
#include "Player.h"

namespace org {
namespace genivi {
namespace mediamanager {


} // namespace mediamanager
} // namespace genivi
} // namespace org
